server:
  port: 8080

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  mvc:
    problem-details:
      enabled: true
logging:
  level:
    web: debug
    org.springframework.security: debug
    top.cgglyle.boson.security: debug
springdoc:
  swagger-ui:
    csrf:
      enabled: true